---
- hosts: all
  tasks:
      - git: repo=https://github.com/bhilburn/powerlevel9k.git
          dest=~/.oh-my-zsh/custom/themes/powerlevel9k
      - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link force=yes
        with_items:
          - bash_aliases
          - bashrc
          - bash_git
          - profile
          - bash_profile
          - zshrc